### ISSUE TITLE
[Feature] 시네머신 배치 및 제어

### ISSUE THREAD

**Issue by KimCastle07** [Gongju-Unity-Bootcamp/Project.998S#135]
# 설명
---
시네머신 기능을 활용하여 제작한 카메라를 실제 스테이지에 배치하고 스크립트 작성을 통해서 상황에 맞는 카메라를 제어하도록 합니다.
# 참고자료
---
- [문서1](https://github.com/neuecc/UniRx)

# 주의사항
---
기존에 있던 코드에 맞게 작성하여야 합니다.

**Comment by 99blanc** [comment]
벌크업한 김세현이 김성현에게 작업을 일임하고 다른 것을 하기로 함.
