### ISSUE TITLE
[Feature] 전투 승리 및 패배 UI 기능 구현

### ISSUE THREAD

**Issue by KimCastle07** [Gongju-Unity-Bootcamp/Project.998S#148]
# 설명
---
전투 승리 및 패배 조건에 맞는 UI 화면을 띄우는 기능을 구현합니다.

# 참고자료
---
- [문서1](https://www.figma.com/file/lG9ldhpCuvYWWnLEhmQQ5z/998's?type=design&node-id=854-3485&mode=design&t=LZjAVd7BD5whFJSO-4)
- [문서2](https://www.figma.com/file/lG9ldhpCuvYWWnLEhmQQ5z/998's?type=design&node-id=533-453&mode=design&t=LZjAVd7BD5whFJSO-4)

# 주의사항
---
전투 승리 시 중앙 기준으로 왼쪽에는 획득한 아이템이 나오게 되고, 3명의 플레이어 초상화를 선택한 후 누구에게 획득 혹은 장착을 할지 결정하는 버튼을 구현해야 합니다.
전투 패배 시 화면의 아무곳이나 클릭을 하여 처음 타이틀 화면으로 돌아오게 구현해야 합니다.

**Comment by 99blanc** [comment]
@murloc5260 시간 상 구현 볼륨을 축소해서 전투 승리 및 패배 UI를 바꿔야 합니다.

**Comment by murloc5260** [comment]
스테이지 클리어시 나오는 UI는 패배 했을 때 나오는 UI와 동일하다
기존에 존재하던 보상 캐릭터 초상화는 삭제 한다

**Comment by 99blanc** [comment]
#158 을 참고해서 구현합니다.
벌크업한 김세현이 작업을 전담합니다.
